REGION_USA = "USA"
REGION_EU = "EU"
REGION_CHINA = "CHINA"

SCHEMAS = "SCHEMAS"
SCHEMA_USA = "SCHEMA_USA"
SCHEMA_EU = "SCHEMA_EU"
SCHEMA_CHINA = "SCHEMA_CHINA"

RAW = "raw"
RAW_EVENTS = "events"
PROCESSED = "processed"
ANALYZED_REGION = "analyzed_region"
ANALYZED_CAR ="analyzed_car"

SCHEMA_TOPIC = "SCHEMA_TOPIC"
SCHEMA_PATH = "SCHEMA_PATH"

TOPICS = "TOPICS"
TOPIC_RAW = "TOPIC_RAW"
TOPIC_PROCESSED = "TOPIC_PROCESSED"
TOPIC_INFO_CAR = "TOPIC_INFO_CAR"
TOPIC_INFO_REGION = "TOPIC_INFO_REGION"

DL_PATHS = "DL_PATHS"
DB_NAME = "DB_NAME"
DB_COLS = "DB_COLS"
REGION_NAME ="REGION_NAME"