REGION_USA = "USA"
REGION_EU = "EU"
REGION_CHINA = "CHINA"

SCHEMAS = "SCHEMAS"
SCHEMA_USA = "SCHEMA_USA"
SCHEMA_EU = "SCHEMA_EU"
SCHEMA_CHINA = "SCHEMA_CHINA"

RAW = "raw"
RAW_EVENTS = "events"
PROCESSED = "processed"
ANALYZED = "analyzed"

SCHEMA_TOPIC = "SCHEMA_TOPIC"
SCHEMA_PATH = "SCHEMA_PATH"


