REGION_USA = "USA"
REGION_EU = "EU"
REGION_CHINA = "CHINA"

SCHEMAS = "SCHEMAS"
SCHEMA_USA = "SCHEMA_USA"
SCHEMA_EU = "SCHEMA_EU"
SCHEMA_CHINA = "SCHEMA_CHINA"

RAW = "raw"
RAW_EVENTS = "events"
PREPROCESSED = "preprocessed"
PROCESSED = "processed"
ANALYZED = "analyzed"

SCHEMA_TOPIC = "SCHEMA_TOPIC"
SCHEMA_PATH = "SCHEMA_PATH"

TOPICS = "TOPICS"
TOPIC_RAW = "TOPIC_RAW"
TOPIC_PROCESSED = "TOPIC_PROCESSED"
TOPIC_INFO_CAR = "TOPIC_INFO_CAR"
TOPIC_INFO_REGION = "TOPIC_INFO_REGION"


